version: 2.1
executors:
  ubuntu:
    docker:
      - image: cimg/base:stable-20.04
jobs:
  circleci_sample_job:
    executor: ubuntu
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            docker run ubuntu:20.10 /bin/echo 'Hello, World!'
workflows:
  version: 2
  circleci_sample_workflow:
    jobs:
      - circleci_sample_job
