version: 2.1

executors:
  ubuntu:
    docker:
      - image: cimg/base:stable-20.04

jobs:
  foobar:
    executor: ubuntu
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            docker run ubuntu:20.10 /bin/echo 'Hello, World!'

workflows:
  version: 2
  hogehoge:
    jobs:
      - foobar
