on:
  push:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
        required: true
        default: 'Default tag'

name: GitHub Actions SSHデバッグ
jobs:
  hello_world_by_docker_run:
    name: Hello, World! by docker run command
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.5
      - name: Hello, World! を標準出力に表示する by docker run
        run: |
          docker run ubuntu:20.10 /bin/echo 'Hello, World!'
      - name: SSH debug
        if: ${{ github.event_name == 'workflow_dispatch' }}
        # https://github.com/marketplace/actions/debugging-with-tmate
        uses: mxschmitt/action-tmate@v3
      - name: echo コマンドを実行する
        run: |
          # echo ${{ github.event.inputs.logLevel }}
          # echo ${{ github.event.inputs.tags }}
          echo 'gh workflow コマンドはpushしたものに対して手元から実行するものであり、実行基盤はリモートである（＝無料時間が消費される）'
