on:
  - push
name: GitHub Actions サンドボックス
jobs:
  hello_world_by_docker_run:
    name: Hello, World! by docker run command
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Hello, World! を標準出力に表示する by docker run
        run: |
          docker run ubuntu:20.10 /bin/echo 'Hello, World!'
